#!/bin/sh

[ "$1" = "" ] && thread="$(xclip -selection clipboard -o)" || thread="$1"

threadnumber=$(echo "$thread" | cut -d/ -f5)
printf "Thread: $threadnumber\n"

export downdir="${XDG_PICTURES_DIR:-$HOME/pix}/Kpopre/$threadnumber/"
[ ! -d "$downdir" ] && mkdir -p "$downdir"

printf "Caching urls...\n"
urls=$(curl -s "$thread" | grep -oiP "https://up\.kpop\.re/src/\K[^/]+/[^/]+\.(jpg|png|mp4|webm)")

download_url() {
    url="$1"
    aria2c -q -c --auto-file-renaming=false --check-certificate=false -d "$downdir" "https://up.kpop.re/src/$url"
    printf "Downloading $url\n"
}

export -f download_url
echo "$urls" | parallel download_url
